# Basic Gitleaks configuration
title = "Gitleaks Config"

[allowlist]
description = "Allowed files"
paths = [
    '''(?i)^\.env\.example$''',
    '''(?i)^test/''',
    '''(?i)^docs/''',
    '''(?i)\.gitleaks.toml$''',
    '''(?i)^SECURITY\.md$'''
]

regexes = [
    '''example''',
    '''sample''',
    '''test''',
    '''dev'''
]
