name: Deploy Arogya AI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Configure Environment
      run: |
        echo "NODE_ENV=production" >> $GITHUB_ENV
      env:
        NODE_ENV: production
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Install Dependencies
      run: npm ci --ignore-scripts
      
    - name: Lint
      run: npm run lint || true
      
    - name: Build
      run: |
        echo "NODE_ENV=production" >> .env
        npm run build
      env:
        CI: true
    
    - name: Create Production Build
      env:
        NODE_ENV: production
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        echo "Creating production build..."
        npm run build
