name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint || echo "No linting configured"

    - name: Run tests
      run: npm test || echo "No tests configured"

    - name: Build
      run: npm run build

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Example deployment to Render (uncomment and configure as needed)
    # - name: Deploy to Render
    #   uses: johnbeynon/render-deploy-action@v0.0.8
    #   with:
    #     service-id: ${{ secrets.RENDER_SERVICE_ID }}
    #     api-key: ${{ secrets.RENDER_API_KEY }}

    # Example deployment to Railway (uncomment and configure as needed)
    # - name: Deploy to Railway
    #   uses: bervProject/railway-deploy@main
    #   with:
    #     railway_token: ${{ secrets.RAILWAY_TOKEN }}